GeneralLong Class Reference
#include <GeneralNumber.h>
Public Member Functions
GeneralLong ()
GeneralLong (long value)
char * toString () const
char * foo () const
GeneralLong * toGeneralLong () const
GeneralRational * toGeneralRational () const
long getValue ()
GeneralNumber * sumWith (GeneralNumber *num)
Private Attributes
long value
Constructor & Destructor Documentation
GeneralLong::GeneralLong ()
Default constructor for GeneralLong
GeneralLong::GeneralLong (long value)
Constructor for GeneralLong
Parameters
value Number to store in the object
Member Function Documentation
char * GeneralLong::foo () const
Demonstrates a non-virtual function.
Returns
Freshly-allocated C-stype string
Referenced by main().
long GeneralLong::getValue ()
Gets the value of this general long
Returns
value of general long
Referenced by sumWith().
GeneralNumber * GeneralLong::sumWith (GeneralNumber * num) [virtual]
Sums two numbers of type GeneralNumber together
Parameters
num pointer to GeneralNumber
Returns
GeneralLong holding resutls of summation
Reimplemented from GeneralNumber .
References getValue(), and GeneralNumber::toGeneralLong().
Referenced by main().
GeneralLong * GeneralLong::toGeneralLong () const [virtual]
Generates an equivalent GeneralLong
Returns
Pointer to a freshly-allocated GeneralLong object
Reimplemented from GeneralNumber .
GeneralRational * GeneralLong::toGeneralRational () const [virtual]
Generates an equivalent GeneralRational
Returns
Pointer to a freshly-allocated GeneralRational object
Reimplemented from GeneralNumber .
Referenced by main().
char * GeneralLong::toString () const [virtual]
Generates a printable representation of the object.
Returns
Freshly-allocated C-stype string
Reimplemented from GeneralNumber .
References MAX_DIGITS_IN_LONG.
Referenced by main().
Member Data Documentation
long GeneralLong::value [private]
The documentation for this class was generated from the following files:
GeneralNumber.h
GeneralNumber.cpp