GeneralNumber Class Reference
#include <GeneralNumber.h>
Public Member Functions
GeneralNumber ()
virtual char * toString () const
char * foo () const
virtual GeneralLong * toGeneralLong () const
virtual GeneralRational * toGeneralRational () const
virtual GeneralNumber * sumWith (GeneralNumber *num)
Constructor & Destructor Documentation
GeneralNumber::GeneralNumber ()
Default constructor for GeneralNumber
Referenced by sumWith().
Member Function Documentation
char * GeneralNumber::foo () const
Demonstrates a non-virtual function.
Returns
Freshly-allocated C-stype string
Referenced by main().
GeneralNumber * GeneralNumber::sumWith (GeneralNumber * num) [virtual]
Default sumWith function. Just returns empty GeneralNumber when called in the GeneralNumber class
Parameters
GeneralNumber* number to sum
Returns
Empty GeneralNumber
Reimplemented in GeneralRational , and GeneralLong .
References GeneralNumber().
GeneralLong * GeneralNumber::toGeneralLong () const [virtual]
Generates an equivalent GeneralLong
Returns
Pointer to a freshly-allocated GeneralLong object
Reimplemented in GeneralRational , and GeneralLong .
Referenced by main(), and GeneralLong::sumWith().
GeneralRational * GeneralNumber::toGeneralRational () const [virtual]
Generates an equivalent GeneralRational
Returns
Pointer to a freshly-allocated GeneralRational object
Reimplemented in GeneralRational , and GeneralLong .
Referenced by GeneralRational::sumWith().
char * GeneralNumber::toString () const [virtual]
Generates a printable representation of the object.
Returns
Freshly-allocated C-stype string
Reimplemented in GeneralRational , and GeneralLong .
Referenced by main().
The documentation for this class was generated from the following files:
GeneralNumber.h
GeneralNumber.cpp