GeneralNumber.cpp File Reference
#include <stdio.h>
*
#include <string.h>
*
#include <stdlib.h>
*
#include `GeneralNumber.h`
*
Functions
long gcd_Helper (long A, long B)
long GCD (long A, long B)
Function Documentation
long GCD (long A, long B)
References gcd_Helper().
Referenced by GeneralRational::canonicalize(), and GeneralRational::sumWith().
long gcd_Helper (long A, long B)
Referenced by GCD().