gntest.cpp File Reference
#include <iostream>
*
#include <stdio.h>
*
#include <stdlib.h>
*
#include `GeneralNumber.h`
*
Functions
int main (int argc, char *argv[])
Function Documentation
int main (int argc, char * argv[])
Program to demonstrate the GeneralNumber class and its subclasses.
Parameters
argc Number of words on the command line.
argv Arrray of pointers to these words.
References GeneralRational::canonicalize(), GeneralNumber::foo(), GeneralLong::foo(), GeneralLong::sumWith(), GeneralRational::sumWith(), GeneralNumber::toGeneralLong(), GeneralLong::toGeneralRational(), GeneralNumber::toString(), GeneralLong::toString(), and GeneralRational::toString().