GeneralRational Class Reference
#include <GeneralNumber.h>
Public Member Functions
GeneralRational ()
GeneralRational (long top, long bottom)
char * toString () const
char * foo () const
GeneralLong * toGeneralLong () const
GeneralRational * toGeneralRational () const
void canonicalize ()
long getTop ()
long getBottom ()
GeneralNumber * sumWith (GeneralNumber *num)
Private Attributes
long top
long bottom
Constructor & Destructor Documentation
GeneralRational::GeneralRational ()
Default constructor for GeneralRational
GeneralRational::GeneralRational (long top, long bottom)
Constructor for GeneralRational
Parameters
top Numerator to store in the object
bottom Denominator to store in the object
Member Function Documentation
void GeneralRational::canonicalize ()
Canonicalizes a GeneralRational Converts the GeneralRational to its canonical form. That is, the rational number is written in its simplest form. If the ratio is negative, the sign is on the numerator, and the denominator is positive.
References GCD().
Referenced by main(), and sumWith().
char * GeneralRational::foo () const
Demonstrates a non-virtual function.
Returns
Freshly-allocated C-stype string
long GeneralRational::getBottom ()
Returns denominator of rational
Returns
Denominator of this general rational
Referenced by sumWith().
long GeneralRational::getTop ()
Returns numerator of rational
Returns
Numerator of this general rational
Referenced by sumWith().
GeneralNumber * GeneralRational::sumWith (GeneralNumber * numInput) [virtual]
Sums this GeneralRational with any GeneralNumber
Parameters
numInput The General Number to sum with
Returns
A GeneralRational summed with this and the input
Reimplemented from GeneralNumber .
References canonicalize(), GCD(), getBottom(), getTop(), and GeneralNumber::toGeneralRational().
Referenced by main().
GeneralLong * GeneralRational::toGeneralLong () const [virtual]
Generates an equivalent GeneralLong
Returns
Pointer to a freshly-allocated GeneralLong object
Reimplemented from GeneralNumber .
GeneralRational * GeneralRational::toGeneralRational () const [virtual]
Generates an equivalent GeneralRational
Returns
Pointer to a freshly-allocated GeneralRational object
Reimplemented from GeneralNumber .
char * GeneralRational::toString () const [virtual]
Generates a printable representation of the object.
Returns
Freshly-allocated C-stype string
Reimplemented from GeneralNumber .
References MAX_DIGITS_IN_LONG.
Referenced by main().
Member Data Documentation
long GeneralRational::bottom [private]
long GeneralRational::top [private]
The documentation for this class was generated from the following files:
GeneralNumber.h
GeneralNumber.cpp