GeneralNumber.h File Reference
Classes
class GeneralNumber
class GeneralLong
class GeneralRational
Macros
#define MAX_DIGITS_IN_LONG (20)
Functions
long GCD (long A, long B)
Macro Definition Documentation
#define MAX_DIGITS_IN_LONG (20)
Referenced by GeneralLong::toString(), and GeneralRational::toString().
Function Documentation
long GCD (long A, long B)
Function that finds GCD and keeps sign intact
Parameters
A first long to find GCD of
B second long to find GCD of
Returns
greatest common divisor
References gcd_Helper().
Referenced by GeneralRational::canonicalize(), and GeneralRational::sumWith().