ArrayHelper.c File Reference
#include `ArrayHelper.h`
*
#include <stdio.h>
*
Functions
int partition (int arr[], int left, int right, int pivot)
Partitions a segment of an array around a pivot number and then returns a pivot index that the array is partitioned around.
void swap (int *element1, int *element2)
Swaps the values of two pointers.
void quickSortHelper (int arr[], int low, int high)
Quick sort function that takes low and high bounds for sort.
void quickSort (int arr[], int size)
Sorts an array in ascending order using quick sort algorithm, in place.
Function Documentation
int partition (int arr[], int left, int right, int pivot)
Partitions a segment of an array around a pivot number and then returns a pivot index that the array is partitioned around.
Author
Ben Hylak
Array Helper class. Contains functions to sort an array using Quick Sort algorithm.
Parameters
left Lower bound of segment
high Upper bound of segment
Pivot value used to split segment
Returns
Index of new pivot
References swap().
Referenced by quickSortHelper().
void quickSort (int arr[], int size)
Sorts an array in ascending order using quick sort algorithm, in place.
Parameters
arr Array to be sorted
size Size of array
References quickSortHelper().
Referenced by main().
void quickSortHelper (int arr[], int low, int high)
Quick sort function that takes low and high bounds for sort.
(Used for sorting segments of an array) Sorts in place.
Parameters
arr Array that segment belongs to
low Lower bound of segment
high Upper bound of segment
References partition().
Referenced by quickSort().
void swap (int * element1, int * element2)
Swaps the values of two pointers.
Parameters
element1 The first pointer
element2 The second pointer
Referenced by partition().