ArrayHelper.h File Reference
Functions
void quickSort (int arr[], int size)
Sorts an array in ascending order using quick sort algorithm, in place.
void swap (int *element1, int *size)
Swaps the values of two pointers.
Detailed Description
Author
Ben Hylak
Header file for ArrayHelper.c
Function Documentation
void quickSort (int arr[], int size)
Sorts an array in ascending order using quick sort algorithm, in place.
Parameters
arr Array to be sorted
size Size of array
References quickSortHelper().
Referenced by main().
void swap (int * element1, int * element2)
Swaps the values of two pointers.
Parameters
element1 The first pointer
element2 The second pointer
Referenced by partition().