at2.c File Reference
#include `ArrayHelper.h`
*
#include `print_arrays.h`
*
#include <stdio.h>
*
#include <stdlib.h>
*
Macros
#define ARRAY_SIZE (10)
Functions
int fillArray (int argc, const char *argv[], int arr[], int maxSize)
Function to fill array with integer data from command line data.
int main (int argc, const char *argv[])
Main program for demonstrating arrays.
Detailed Description
Part 2+3 of Assignment 2 for CS2303.
Author
Ben Hylak
Takes a list of integers from the command line, prints the inputted numbers, sorts the numbers (quicksort) and then prints again.
Macro Definition Documentation
#define ARRAY_SIZE (10)
Referenced by main().
Function Documentation
int fillArray (int argc, const char * argv[], int arr[], int maxSize)
Function to fill array with integer data from command line data.
Parameters
argc Argument count from command line
argv Arguments from command line
arr Array to fill
maxSize Max size of the array, so the function knows when to stop filling
Returns
Number elements were inserted into the array
Referenced by main().
int main (int argc, const char * argv[])
Main program for demonstrating arrays.
It fills them and prints them.
Returns
0, Indicating success.
References ARRAY_SIZE, fillArray(), print_int_array(), and quickSort().