at3.c File Reference
#include `ArrayHelper.h`
*
#include `print_arrays.h`
*
#include <stdio.h>
*
#include <stdlib.h>
*
#include <time.h>
*
Macros
#define MAX_ARRAY_SIZE (20)
#define MAX_RANDOM_INT 200
Functions
int getRandomInt (int max)
void fillArrayRandom (int arr[], int maxSize)
int main ()
Main program for demonstrating arrays.
Macro Definition Documentation
#define MAX_ARRAY_SIZE (20)
Part 4 Assignment 2 for CS2303.
Author
Ben Hylak
Generates an array of random integers, prints them, sorts them, and then prints again.
Referenced by main().
#define MAX_RANDOM_INT 200
Referenced by fillArrayRandom().
Function Documentation
void fillArrayRandom (int arr[], int maxSize)
Fills arrays with random ints
Parameters
arr Array to fill
maxSize Max size of the array, so the function knows when to stop filling
References getRandomInt(), and MAX_RANDOM_INT.
Referenced by main().
int getRandomInt (int max)
Gets random integer Function gets a pseudo random integer from 0 to specific maximum, inclusive.
Parameters
max Maximum random integer can be
Returns
Psuedo random int
Referenced by fillArrayRandom().
int main ()
Main program for demonstrating arrays.
It fills them and prints them.
Returns
0, Indicating success.
References fillArrayRandom(), MAX_ARRAY_SIZE, print_int_array(), and quickSort().