mystring.c File Reference
#include <string.h>
*
#include <stdlib.h>
*
#include `mystring.h`
*
#include <stdio.h>
*
Functions
char * mystrdup (const char *src)
char * movePointerToTerminator (char *str1)
int myStrLen (const char *src)
const char * myStrCpy (const char *dest, const char *src)
const char * myStrCat (const char *dest, const char *src)
Function Documentation
char* movePointerToTerminator (char * str1)
! Increments a char pointer until it equals the null terminator, then returns pointer
Parameters
str1 pointer to char array
Returns
pointer to null terminator
Referenced by myStrCat().
const char* myStrCat (const char * dest, const char * src)
References movePointerToTerminator().
Referenced by main().
const char* myStrCpy (const char * dest, const char * src)
! Copies the characers from src into destination, including the null terminator.
The strcpy() function copies the string pointed to by src, including the terminating null byte ('\0'), to the buffer pointed to by dest. The strings may not overlap, and the destination string dest must be large enough to receive the copy. Beware of buffer overruns!
Parameters
dest Array copied into
src Array copied from
Returns
char* Array copied into
Referenced by main().
char* mystrdup (const char * src)
mystring.c
Author
Mike Ciaraldi My own versions of some of the C-style string functions Duplicates a C-style string.
Parameters
src Pointer to string to be copied
Returns
Pointer to freshly-allocated string containing a duplicate of src or null if no memory is available
Referenced by main().
int myStrLen (const char * src)
! Counts the number of characters in a string excluding the null terminator.
Parameters
src String to count characters of
Returns
length of string
Warning
string must have null terminator
Referenced by main().