mystring.h File Reference
Functions
char * mystrdup (const char *src)
char * myStrCat (char *dest, const char *src)
int myStrLen (const char *src)
char * myStrCpy (char *dest, const char *src)
Function Documentation
char* myStrCat (char * dest, const char * src)
! Appends the src string to the dest string
Appends the src string to the dest string, overwriting the terminating null byte ('\0') at the end of dest, and then adds a terminating null byte.
Parameters
dest String that will have src appended to the end
src String that will be appended to the end of dest
Returns
Pointer to result string
Warning
If dest is not large enough, program behavior is unpredictable; buffer overruns are a favorite avenue for attacking secure programs
References myStrLen().
Referenced by main().
char* myStrCpy (char * dest, const char * src)
Copies string starting at address of dest
Parameters
dest Address string is copied into
src String to copy
Returns
address of copied string
Warning
src must be null terminated
Referenced by main().
char* mystrdup (const char * src)
mystring.h
Author
Mike Ciaraldi My own versions of some of the C-style string functions
mystring.c
Author
Mike Ciaraldi My own versions of some of the C-style string functions Duplicates a C-style string.
Parameters
src Pointer to string to be copied
Returns
Pointer to freshly-allocated string containing a duplicate of src or null if no memory is available
Referenced by main().
int myStrLen (const char * dest)
Counts the length of a string
Parameters
dest String to count
Returns
Length of String
Warning
string must be null terminated
Referenced by main(), and myStrCat().